### ISSUE TITLE
How many songs in phonk.live is available???

### ISSUE THREAD

**Issue by SagXD** [SashaRyder/Docker-Radio#1]

**Comment by ATypescriptEnjoyer** [comment]
You can see the number of tracks loaded in the stats area, 733 tracks are available. ![image](https://user-images.githubusercontent.com/8694395/179188614-44fd8872-7357-405f-9d95-1b398799c2be.png)

These tracks are not committed to source control, Docker-Radio only provides the base code which phonk.live sits on top of
